AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pipeline para extraer datos de Twitter para mi tesis.

Resources:
  extractordatosx:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: extractor-datos-x
      CodeUri: src/
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaTesisExtraccionX"
      Events:
        HourlyTrigger:
          Type: Schedule
          Properties:
            Schedule: "cron(0 * * * ? *)"
      Timeout: 60
      MemorySize: 256
    Metadata:
      BuildMethod: python_pip