
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Pipeline de recolección continua y optimizada para la tesis de Arturo Gonzalez Lattuada.

Resources:
  DataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TesisTwitterData
      AttributeDefinitions: [{AttributeName: tweet_id, AttributeType: S}]
      KeySchema: [{AttributeName: tweet_id, KeyType: HASH}]
      BillingMode: PAY_PER_REQUEST

  StateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TesisTwitterState
      AttributeDefinitions: [{AttributeName: id, AttributeType: S}] # Una clave genérica
      KeySchema: [{AttributeName: id, KeyType: HASH}]
      BillingMode: PAY_PER_REQUEST

  extractordatosx:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: extractor-datos-x
      CodeUri: src/
      Handler: funcion_lambda_extraccion_x.lambda_handler
      Runtime: python3.12
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaTesisExtraccionX"
      Timeout: 900
      MemorySize: 256
      Events:
        FifteenMinuteTrigger: # Renombramos el trigger
          Type: Schedule
          Properties:
            # CAMBIO: Ejecutar cada 15 minutos
            Schedule: "rate(15 minutes)"
            Enabled: true
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DataTable
        - DynamoDBCrudPolicy:
            TableName: !Ref StateTable
    Metadata:
      BuildMethod: python_pip