name: Deploy Lambda to AWS

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      # LA LÍNEA MÁS IMPORTANTE A VERIFICAR ES LA SIGUIENTE:
      - name: Build with SAM
        run: sam build --use-container

      - name: Deploy with SAM
        run: sam deploy --no-confirm --stack-name tesis-x-pipeline --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}