name: MANUAL DEPLOY - Build and Deploy Lambda

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  manual-build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 3. Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 4. Manually build dependencies and create deployment package
        run: |
          # Instalar dependencias en un directorio específico
          pip install -r requirements.txt -t ./package
          # Copiar el código de la función a ese directorio
          cp -r src/* ./package/
          # Crear el archivo .zip desde dentro del directorio 'package'
          cd package
          zip -r ../deployment_package.zip .

      - name: 5. Deploy package to AWS Lambda
        # Usamos la AWS CLI para actualizar el código de la función directamente
        # Asegúrate que el nombre de la función aquí sea el correcto en tu consola de AWS
        run: >
          aws lambda update-function-code 
          --function-name twitter-data-extractor
          --zip-file fileb://deployment_package.zip