name: DIAGNOSE - Validate SAM Template

on:
  push:
    branches:
      - master

jobs:
  validate-template:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Check workspace files
        run: |
          echo "--- Listing files in root directory ---"
          ls -la
          echo "---------------------------------------"

      - name: 3. Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: 4. Check File Encoding and Hidden Characters
        run: |
          echo "--- Checking file encoding (should be utf-8 or us-ascii) ---"
          file --mime-encoding template.yaml
          echo "------------------------------------------------------------"
          echo "--- Printing file content with hidden characters visible ---"
          # cat -A muestra $ al final de las líneas y ^I para tabs, etc.
          cat -A template.yaml
          echo "------------------------------------------------------------"

      - name: 5. Run SAM Validate
        # Este es el paso más importante. Forzará un error claro y específico.
        # Le añadimos --debug para máxima verbosidad.
        run: sam validate --template template.yaml --debug